DROP DATABASE IF EXISTS Fresher;
CREATE DATABASE IF NOT EXISTS Fresher;
USE Fresher;

DROP TABLE IF EXISTS Trainee;
CREATE TABLE Trainee (
	TraineeID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Full_Name NVARCHAR(50) NOT NULL,
    Birth_Date DATE NOT NULL,
    Gender ENUM('male', 'female', 'unknown') NOT NULL,
    ET_IQ TINYINT UNSIGNED CHECK(ET_IQ <= 20) NOT NULL,
    ET_Gmath TINYINT UNSIGNED CHECK(ET_Gmath <= 20) NOT NULL,
    ET_English TINYINT UNSIGNED CHECK(ET_English <= 50) NOT NULL,
    Training_Class VARCHAR(10) NOT NULL,
    Evaluation_Notes TEXT(100) NOT NULL
);

ALTER TABLE Trainee 
ADD COLUMN VTI_Account VARCHAR(50) NOT NULL UNIQUE;

/*
Exercise 2:
ID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(50)NOT NULL,
Code CHAR(5) NOT NULL,
ModifiedDate DATATIME DEFAULT NOW()	

Exercise 3:
ID TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
BirthDate DATE NOT NULL,
Gender ENUM('0', '1', '2'), --0: Male, 1: Female, 2: Unknown
IsDeleteFlag ENUM('0', '1') DEFAULT 0 --0: Active, 1: Delete
*/



